// <auto-generated />
using System;
using JoinClassGestaodeHorario.API.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JoinClassGestaodeHorario.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260609010440_AddTipoUsuario")]
    partial class AddTipoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_usuario", new[] { "aluno", "professor", "coordenador", "diretor" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Disciplina", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("carga_horaria")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("disciplina", "public");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Disponibilidade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("dia_semana")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("horario_fim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("horario_inicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_professor")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("id_professor");

                    b.ToTable("disponibilidade", "public");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Graduacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("duracaoGraduacao")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_graduacao");

                    b.Property<int>("idCoordenador")
                        .HasColumnType("integer")
                        .HasColumnName("id_coordenador");

                    b.Property<string>("nomeGraduacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_graduacao");

                    b.Property<int>("qntAulaGraduacao")
                        .HasColumnType("integer")
                        .HasColumnName("qnt_aula_graduacao");

                    b.HasKey("id");

                    b.HasIndex("idCoordenador");

                    b.ToTable("graduacao", "public");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Horario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("dia_semana")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("horario_fim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("horario_inicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idTurma")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("idTurma");

                    b.ToTable("horario", "public");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.MatrizCurricular", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("idDisponibilidade")
                        .HasColumnType("integer");

                    b.Property<int>("idGraduacao")
                        .HasColumnType("integer");

                    b.Property<int>("idSemestre")
                        .HasColumnType("integer");

                    b.Property<string>("nomeMatrizCurricular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("idDisponibilidade");

                    b.HasIndex("idGraduacao");

                    b.HasIndex("idSemestre");

                    b.ToTable("matriz_curricular", "public");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Pessoa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("pessoa", "public");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.ProfessorDisciplina", b =>
                {
                    b.Property<int>("id_professor")
                        .HasColumnType("integer");

                    b.Property<int>("id_disciplina")
                        .HasColumnType("integer");

                    b.HasKey("id_professor", "id_disciplina");

                    b.HasIndex("id_disciplina");

                    b.ToTable("professor_disciplina", "public");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Semestre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("periodo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("semestre", "public");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Titulacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("id_professor")
                        .HasColumnType("integer");

                    b.Property<string>("tipoTitulacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("id_professor");

                    b.ToTable("titulacao", "public");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Turma", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("MatrizCurricularid")
                        .HasColumnType("integer");

                    b.Property<int>("idMatrizCurricular")
                        .HasColumnType("integer");

                    b.Property<int>("id_professor")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("MatrizCurricularid");

                    b.HasIndex("idMatrizCurricular");

                    b.HasIndex("id_professor");

                    b.ToTable("turma", "public");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.TurmaAluno", b =>
                {
                    b.Property<int>("idTurma")
                        .HasColumnType("integer");

                    b.Property<int>("idAluno")
                        .HasColumnType("integer");

                    b.HasKey("idTurma", "idAluno");

                    b.HasIndex("idAluno");

                    b.ToTable("turma_aluno", "public");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Aluno", b =>
                {
                    b.HasBaseType("JoinClassGestaodeHorario.API.Dominio.Entidade.Pessoa");

                    b.ToTable("aluno", "public");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Coordenador", b =>
                {
                    b.HasBaseType("JoinClassGestaodeHorario.API.Dominio.Entidade.Pessoa");

                    b.ToTable("coordenador", "public");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Professor", b =>
                {
                    b.HasBaseType("JoinClassGestaodeHorario.API.Dominio.Entidade.Pessoa");

                    b.ToTable("professor", "public");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Disponibilidade", b =>
                {
                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Professor", "Professor")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("id_professor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Graduacao", b =>
                {
                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Coordenador", "Coordenador")
                        .WithMany("Graduacoes")
                        .HasForeignKey("idCoordenador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordenador");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Horario", b =>
                {
                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Turma", "Turma")
                        .WithMany("Horarios")
                        .HasForeignKey("idTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.MatrizCurricular", b =>
                {
                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Disponibilidade", "Disponibilidade")
                        .WithMany()
                        .HasForeignKey("idDisponibilidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Graduacao", "Graduacao")
                        .WithMany("Matrizes")
                        .HasForeignKey("idGraduacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Semestre", "Semestre")
                        .WithMany()
                        .HasForeignKey("idSemestre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disponibilidade");

                    b.Navigation("Graduacao");

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.ProfessorDisciplina", b =>
                {
                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Disciplina", "Disciplina")
                        .WithMany("ProfessorDisciplinas")
                        .HasForeignKey("id_disciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Professor", "Professor")
                        .WithMany("ProfessorDisciplinas")
                        .HasForeignKey("id_professor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Titulacao", b =>
                {
                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("id_professor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Turma", b =>
                {
                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.MatrizCurricular", null)
                        .WithMany("Turmas")
                        .HasForeignKey("MatrizCurricularid");

                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.MatrizCurricular", "MatrizCurricular")
                        .WithMany()
                        .HasForeignKey("idMatrizCurricular")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("id_professor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatrizCurricular");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.TurmaAluno", b =>
                {
                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Aluno", "Aluno")
                        .WithMany("TurmaAlunos")
                        .HasForeignKey("idAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Turma", "Turma")
                        .WithMany("TurmaAlunos")
                        .HasForeignKey("idTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Aluno", b =>
                {
                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("JoinClassGestaodeHorario.API.Dominio.Entidade.Aluno", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Coordenador", b =>
                {
                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("JoinClassGestaodeHorario.API.Dominio.Entidade.Coordenador", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Professor", b =>
                {
                    b.HasOne("JoinClassGestaodeHorario.API.Dominio.Entidade.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("JoinClassGestaodeHorario.API.Dominio.Entidade.Professor", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Disciplina", b =>
                {
                    b.Navigation("ProfessorDisciplinas");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Graduacao", b =>
                {
                    b.Navigation("Matrizes");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.MatrizCurricular", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Turma", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("TurmaAlunos");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Aluno", b =>
                {
                    b.Navigation("TurmaAlunos");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Coordenador", b =>
                {
                    b.Navigation("Graduacoes");
                });

            modelBuilder.Entity("JoinClassGestaodeHorario.API.Dominio.Entidade.Professor", b =>
                {
                    b.Navigation("Disponibilidades");

                    b.Navigation("ProfessorDisciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
